### PR TITLE
Update hovering actions on wire ports + Rewrite guardrail validation design in Encre

### PR DESCRIPTION
**Pull request by VictorS67**
some changes:

EncreUI:
- Now the wire port is changing its background color (e.g. from blue to black) when the user is hovering on the port.

Encre Core:
- Change `VariableValidator` into a Callable.
- Remove `partialVariables` from `BasePromptTemplate` since we didn't use it so far.
- Now `BasePromptTemplate` holds the metadata (i.e. the `rules` variable in `VariableValidator`) instead of the `VariableValidator`. When the prompt template gets invoked, it first check if the metadata (e.g. `guardrails`) is set to enable the validator. Then it scans the prompt template to find all variable names (e.g. variable is in a format of `{{XXX}}`, where `XXX` is the variable name), instantitiating a new `VariableValidator` with the variable names and `guardrails`, then check the validation. If the validation fails, throw the error.
- Adding guardrails as the `BaseRule` serializable in Encre. These are used for any validation, such as `VariableValidator`, `BasePromptTemplate`, etcs.

### CODE REVIEW

**Comment by VictorS67** [comment]
# Guardrails in Encre

## Overview
Inspired by [Guardrails AI](https://www.guardrailsai.com/docs), guardrails in Encre are used for validating a node's input or output. In real-world cases, we may require the Encre application to be able of detecting, quantifying, and migitating specific types of risks. Those risks could be code-specific (e.g. type checking, greater/less than, equal/not equal, etcs.), or boarder risks (sexual violation, off-topic, hallucinations, etcs). This guardrails are designed as rules for validating such risks.

Note: this PR only add code-specific rules. More rules can be added in the future.

## Key Concept
- Guardrail/Rule: A serializable class that holds a description, metadata variables used in validation function, and an async validation function.

## Current Avaliable Guardrails

### GeneralRule
It takes an `unknown` type as input to the validation. This can be oftenly used for customizing any guardrails.

### StringRule
It takes a `string` type as input to the valdiation. There are some pre-defined guardrails:

- exists
- doesn't exist
- is equal to
- isn't equal to
- contains
- doesn't contain
- starts with
- doesn't start with
- ends with
- doesn't end with
- matches regex
- doesn't match regex
- length equal to
- length not equal to
- length greater than
- length less than
- length greater than or equal
- length less than or equal

### NumberRule
It takes a `number` type as input to the valdiation. There are some pre-defined guardrails:

- exists
- doesn't exist
- is equal to
- isn't equal to
- is greater than
- is less than
- is greater than or equal
- is less than or equal

### BooleanRule
It takes a `boolean` type as input to the valdiation. There are some pre-defined guardrails:

- exists
- doesn't exist
- is true
- is false
- is equal to
- isn't equal to

### JSONObjectRule
It takes a `obejct` type as input to the valdiation. There are some pre-defined guardrails:

- exists
- doesn't exist
- is empty
- isn't empty
- is equal to
- isn't equal to

### ArrayRule
It takes a `Array<unknown>` type as input to the valdiation. There are some pre-defined guardrails:

- exists
- doesn't exist
- is equal to
- isn't equal to
- contains
- doesn't contain
- length equal to
- length not equal to
- length greater than
- length less than
- length greater than or equal
- length less than or equal

## Merging two rules
If you want to apply two (or more) rules to a single input, you can merge them together by `concat`. This is an example:

```TypeScript
// Suppose I have a rule to check if the input is a string, and I also want to check if it equals 'John'
const isStringRule = new GeneralRule({
  description: 'is string',
  func: async (input: unknown) => {
    return typeof input === 'string';
  },
});

const isJohnRule = new GeneralRule({
  description: 'is John',
  func: async (input: string) => {
    return input === 'John';
  },
});

// Use `concat` with a 'and' conjunction can merge two rules
const newRule = isStringRule.concat(isJohnRule, 'and');

expect(newRule.description).toBe('is string AND is John');
expect(await newRule.validate('John')).toBeTruthy();
expect(await newRule.validate('Peter')).toBeFalsy();
```

You can see that the merged rule (e.g. `newRule`) has merged description (e.g. `'is string AND is John'`) and merged validation function (and merged variables, the following example is showing this).

If you have any variables in your rules, then variables are wrapped in `left` or `right` attribute in the new `variables` object, depending on the position that you put the rules in concat. This is an example:

```TypeScript
const isStringRule = new GeneralRule({
  description: 'is string',
  func: async (input: unknown) => {
    return typeof input === 'string';
  },
});

// Instead of checking if the input is John, I want the name to be flexible
const isSomeNameRule = new GeneralRule({
  description: 'is {{name}}',
  variables: { name: 'John' },
  func: async (input: string, variables: { name: string }) => {
    return input === variables.name;
  },
});

expect(await isSomeNameRule.validate('John')).toBeTruthy();
expect(await isSomeNameRule.validate('Peter')).toBeFalsy();

// Use `concat` with a 'and' conjunction can merge two rules
const newRule = isStringRule.concat(isSomeNameRule, 'and');

// The variable in `isSomeNameRule` is wrapped in the `right` attribute, because
// `isSomeNameRule` is the right rule when merging
expect(newRule.variables).toStrictEqual({
  left: {},
  right: { name: 'John' },
});
expect(await newRule.validate('John')).toBeTruthy();
expect(await newRule.validate('Peter')).toBeFalsy();

// Now I want to change the name to be 'Peter' instead of 'John'
newRule.variables = { left: {}, right: { name: 'Peter' } };

expect(await newRule.validate('John')).toBeFalsy();
expect(await newRule.validate('Peter')).toBeTruthy();
```

Now you should know the position of the rules is very important in merging, because of two reasons:

1. The variables are wrapped into either 'left' or 'right' depending on the position;
2. The description is also wrapped with 'AND' or 'OR' along with brackets from left to right rules.

Make sure that you can always keep track of the variables, when you want to combine more rules into one.

**Review by BenWXY — APPROVED** [review]

**Comment by AlveinTeng** [comment]
What if people try to concat two contradictory rules?

**Review by AlveinTeng — APPROVED** [review]
For validation, what if user try to concat contradictory rules?

**Comment by VictorS67** [comment]
> What if people try to concat two contradictory rules?

It depends on the conjuction (AND/OR) that people added when merging the rules. If it is OR, then either RuleA or RuleB will validate the input. If it is AND, then both RuleA and RuleB are validating the input.

**Pull request merged**
