### PR TITLE
Add Encre Studio core functionalities

### PR DESCRIPTION
**Pull request by VictorS67**

### CODE REVIEW

**Comment by VictorS67** [comment]
# Data Typing and Manipulation Utilities

## Overview
In the Encre Studio, we define our own data typing and manipulation utilities to handle the dataflow in the Encre node-graph system.

This documentation covers the definitions of scalar and array data types, type guards, conversion utilities, and default values. It aims to standardize data handling across different modules, enhancing type safety and code readability.

## Data Types
The Encre Studio categorizes data into scalar and array types, encompassing a wide range of commonly used data types.

### Scalar Data Types
Scalar data types represent single values and include the following:

- `StringData`
- `NumberData`
- `BooleanData`
- `UnknownData`
- `JSONObjectData`
- `BlobData`
- `ContextData`
- `ChatMessageData`

Each scalar data type is defined using the `DataDef<T, RuntimeType>` interface, where `T` is a string literal representing the type (e.g. `'string'`, `'chat-message'`, etcs), and `RuntimeType` is the corresponding JavaScript runtime type (e.g. `string`, `BaseMessage` in TypeScript).

### Array Data Types
Array data types represent arrays of scalar data types. The utility dynamically generates array data types based on the defined scalar types, allowing for types like `StringData[]`, `NumberData[]`, etc. Each scalar data type has its own array data type in the `DataDef<T, RuntimeType>` interface. For example, the array of `StringData` has a string literal representing type `'string[]'` and the corresponding JavaScript runtime type `string` in TypeScript.

## Utility Functions
The utilities include type guards, conversion functions, and functions to get default values for each data type.

### Type Guards
- `isArrayData(data: Data | undefined): data is ArrayData`
- `isArrayDataType(type: DataType): type is ArrayDataType`
- `isScalarData(data: Data | undefined): data is ScalarData`
- `isScalarDataType(type: DataType): type is ScalarDataType`

These functions help determine the kind of data or data type, facilitating runtime type checks and ensuring correct type handling in the code.

### Conversion Functions
- `getScalarTypeOf(type: DataType): ScalarDataType`
- `toScalarFromArray(arrayType: ArrayDataType): ScalarDataType`
- `toArrayFromScalar(scalarType: ScalarDataType): ArrayDataType`
- `arrayizeData(data: Data): ScalarData[]`

Conversion functions are essential for working with the defined data types, allowing developers to switch between scalar and array types or to normalize data into a consistent format.

### Default Values
- `getDefaultValue<T extends DataType>(type: T): (Data & { type: T })['value']`

This function provides a default value for a given data type, useful for initialization and ensuring type safety when data might be undefined or null.

## When and where to use these data types
If you are dealing with data values defined in nodes (e.g. `NodeImpl` or `CallableNodeImpl`), you should alway ensure that the data values are in those data types. Any data tranferring from ports to ports between nodes are also defined in those data types.

**Comment by VictorS67** [comment]
# Data Coercion Utilities

## Overview
This documentation outlines the implementation and usage of data coercion utilities within the Encre Studio. These utilities are designed to facilitate the conversion of various data types into a unified data model, enhancing consistency, type safety, and interoperability across the node graph system.

## Introduction
The data coercion utilities provide a robust framework for converting `unknown` values into strongly typed data structures defined within the Encre Studio. These conversions are crucial for handling dynamic data sources and ensuring that data manipulation and processing are performed safely and predictably.

## Core Concepts

### Data Types
- **ScalarData:** Represents single-value data types, including primitives like strings, numbers, and booleans, as well as complex types like blobs and custom objects like `Context` and `BaseMessageLike`.
- **ArrayData:** Represents arrays of scalar data types, facilitating the handling of collections of data uniformly.
- **Data:** A union type that encompasses both `ScalarData` and `ArrayData`, providing a flexible structure for representing any data within the system.

### Utilities
- `coerceToData(value)`: Converts an `unknown` value into a `Data` type, categorizing it as either `ScalarData` or `ArrayData` based on its runtime value.
- `coerceTypeOptional(data, type)`: Asynchronously coerces `Data` into a specified `DataType`, allowing for flexible type conversions with optional fallbacks.
- `expectTypeOptional(data, type)`: Verifies that a piece of data matches an expected `DataType`, returning the data if it matches, or throwing an error otherwise.

## Utility Functions

### `coerceToData`
Converts any `unknown` value into a structured `Data` type, determining the most appropriate type based on the runtime characteristics of the value.

#### Parameters
- **value:** The `unknown` value to be coerced into a `Data` type.

#### Returns
- **Data:** A `ScalarData` or `ArrayData` instance representing the original value in a structured format.

#### Usecases
```TypeScript
const data: number = 42; // number
const numberValue = coerceToData(data); 
// `numberValue` should be { type: 'number', value: 42 }
```

### `coerceTypeOptional`
Asynchronously attempts to coerce a `Data` instance into a specified `DataType`, handling both scalar and array types and providing fallback mechanisms for type conversion.

#### Parameters
- **data:** The `Data` instance to be coerced.
- **type:** The target `DataType` to coerce the data into.

#### Returns
- A Promise resolving to the coerced value in the specified type, or `undefined` if the coercion cannot be completed.

#### Usecases
```TypeScript
const data = { type: 'number', value: 42 }; // NumberData
const stringValue = await coerceTypeOptional(data, 'string'); 
// `stringValue` should be '42'
```

### `expectTypeOptional`
Asynchronously asserts that a given piece of data matches an expected `DataType`, facilitating type checks and validations across the system.

#### Parameters
- **data:** The `Data` instance to be checked.
- **type:** The expected `DataType`.

#### Returns
- A Promise resolving to the value if it matches the expected type, or `undefined` if the data is not present. Throws an error if the data type does not match.

#### Usecases
```TypeScript
const data = { type: 'number', value: 42 }; // NumberData
const stringValue = await expectTypeOptional(data, 'string'); 
// Error! `Expect data of type string but instead got number`
```

**Comment by VictorS67** [comment]
# Node Architecture for Serializable and Callable

## Overview

This documentation provides an overview of the node architecture for Serializable and Callable in the Encre Studio core logic. It covers the fundamental components, including the base node structure, node types, port definitions, node connections, and implementation classes. This architecture is designed to facilitate flexible, modular data processing and manipulation across various project components.

## Key Components

### `BaseNode`

`BaseNode` is the foundational structure for all node types. It contains visual information for rendering in a UI, such as position and size, and defines the structure for input and output ports.

#### Structure

- `visualInfo`: Contains the node's position (`x`, `y`, and optionally `zIndex`) and size (`width` and `height`).
- `inputs`: An optional mapping of input port fields, specifying the data type for each input. If undefined or empty, then the node does not have any input.
- `outputs`: An optional mapping of output port fields, specifying the data type for each output. If undefined or empty, then the node does not have any output.

### `SerializableNode` and `CallableNode`

These interfaces extend `BaseNode` to define nodes with specific capabilities:

- `SerializableNode`: Any Node in the Encre Studio can be serialized, containing a `type` and `data` field. The `type` is a string, and the `data` is a `Serializable` class object.
- `CallableNode`: A specialized type of `SerializableNode` intended for nodes that can be invoked with input to produce output. The `data` field is a `Callable` class object.

### Node Port Definitions

Defines the structure for input and output ports of a node.

- `NodeInputPortDef` or `NodeOutputPortDef`: Contains the node ID, name, type, optional data, and a default value.

### Node Connection (not finalized yet)

Describes a connection between two nodes, mapping an output port of one node to an input port of another.

### `NodeImpl` and `CallableNodeImpl`

Abstract classes that provide a template for implementing nodes' functionality.

- `NodeImpl`: Base implementation for a `SerializableNode`, handling initialization, attribute management, and input/output definitions.
- `CallableNodeImpl`: Extends `NodeImpl` to add support for a `CallableNode`, including preprocessing and postprocessing of inputs and outputs, and invoking the `Callable`.

## Usage

To utilize this node architecture in the Encre Studio, developers should:

1. **Define Node Types:** Create specific node types by extending `SerializableNode` or `CallableNode` interfaces with relevant data and functionality.
2. **Implement Node Logic:** Use `NodeImpl` or `CallableNodeImpl` to provide concrete implementations for the node's process logic or callable actions.
3. **Connect Nodes:** Utilize `NodeConnection` to define data flow between nodes, linking output ports to input ports across different nodes. (not finalized yet)

**Comment by VictorS67** [comment]
# Node Implementation

## Overview

This document provides a comprehensive guide to the `NodeImpl` and `CallableNodeImpl` classes. These abstract classes are designed to facilitate the development of a modular, scalable, and flexible node-based system for data processing and callable operations. The framework supports a wide range of applications, from simple data manipulation tasks to complex workflows involving serializable and callable nodes.

## `NodeImpl` Class

The `NodeImpl` class serves as a base for all nodes within the Encre Studio (e.g. `SerializableNode`), encapsulating common properties and functionalities needed for node operation, including serialization, data management, and input/output processing.

### Key Features

- **Data and Type Management:** It manages node data and types, providing a structured approach to handling node-specific information.
- **Keyword Arguments (kwargs):** Supports dynamic keyword arguments for flexible node configuration and operation.
- **Port Definitions:** Dynamically generates input and output port definitions based on the node's configuration.
- **Input Validation:** Offers a method to validate inputs against the node's expected inputs, ensuring data integrity and correctness.

### Implementation Details

- **Constructors:** Initializes a node instance with essential properties including aliases, secrets, and kwargs derived from the node's data.
- **Property Accessors:** Provides access to node ID, type, name, visual info, data, inputs, outputs, and kwargs.
- **Update Keyword Arguments Method:** `setKwargs(key, value)` for setting or updating keyword arguments for the node.
- **Port Definition Methods:** `getInputPortDefs()` and `getOutputPortDefs()` for defining how data enters and exits the node.
- **Input Validation Method:** `validateInputs(inputs)` for checking if provided inputs match the node's requirements.

## `CallableNodeImpl` Class

Extending `NodeImpl`, the `CallableNodeImpl` class is specified for nodes that perform callable operations, adding functionality to invoke actions based on the node's inputs and internal logic.

### Key Features

- **Callable Operations:** Designed to handle nodes that execute operations, potentially involving external services or complex processing logic.
- **Preprocessing and Postprocessing:** Abstract methods for input preprocessing and output postprocessing, allowing custom logic to be applied before and after the main operation.
- **Invocation:** An abstract `invoke` method to carry out the node's callable action, taking inputs and producing outputs according to the node's design.

### Implementation Details

- **Constructor:** Inherits the `NodeImpl` constructor and adds initialization for callable-specific metadata.
- **Callable Type:** Accessor for the node's callable type, providing insight into the operation's nature.
- **Abstract Methods:**
  - `_preprocess(inputs, context)`: Prepares inputs for processing the `invoke` function within the `Callable` class object. Since the Callable class object does not require defined data types in Nodes, inputs should be unwrapped into data values in runtime types. This step should be handled in this method.
  - `_postprocess(rawOutputs, context)`: Handles raw outputs after the `invoke` function within the `Callable` class object is complete. We requires all data in the Nodes should be defined data types, raw outputs should be wrapped into defined data. This step should be handled in this method.
  - `invoke(input, options)`: Executes the `invoke` function within the `Callable` class object, defined by extending classes to fit specific requirements.

## Usage

To utilize this node implementation in the Encre Studio, developers should:

1. **Implement Specific Nodes:** Create classes that extend `NodeImpl` or `CallableNodeImpl`, providing concrete implementations for abstract methods and custom logic tailored to the node's purpose.
2. **Define Node Properties:** Specify properties such as `type`, `data`, and port configurations to match the intended use of the node.
3. **Customize Data Processing:** Implement custom logic for data processing, callable operations, input validation, and kwargs management as needed.

**Comment by VictorS67** [comment]
# Loader Nodes

## Overview

This document outlines the implementation and usage of loader nodes in the Encre Studio class. Loader nodes supports a callable event extends `BaseLoader` designed to load various types of data.

## `LoaderNode` Type

`LoaderNode` is a specific callable node type intended for loading operations. It is defined with a generic `'loader'` type and associated with a base loader class, `BaseLoader`, which can be extended to support different data formats.

### Key Features

- **Generic Loader Type:** Facilitates the creation of loader nodes for various data formats.
- **Extensibility:** Allows for easy extension to accommodate different types of loaders, such as PDFs.

## `LoaderNodeImpl` Class

`LoaderNodeImpl` is an abstract base class for all loader node implementations. It extends from `CallableNodeImpl`, inheriting its callable functionalities while focusing on data loading operations.

## `PDFLoaderNodeImpl` Class

`PDFLoaderNodeImpl` is a concrete implementation of the `LoaderNodeImpl` class, specifically designed for loading PDF documents.

### Creation

- `create()`: Static method to instantiate a `LoaderNode` configured for PDF loading. It sets up the node's type, associated data (loader configuration), visual information, inputs, and outputs. This is used for creating a default PDF node.
  - **Input Ports:** has one port named `pdf`, allowing either of two types: `StringData` or `BlobData`;
  - **Output Ports:** has one port named `contexts`, allowing a single type: array of `ContextData`.

### Processing Methods

1. `_preprocess(inputs, context)`: Prepares the input data for processing, ensuring it is either a `string` or a `Blob`. Throws an error for invalid inputs.
2. `_postprocess(rawOutputs, context)`: Handles the outputs from the loading operation, converting them into a structured format suitable for further processing.
3. **`invoke(input, options)`**: Performs the actual loading operation using the provided input, which must be a `string` or a `Blob`.
4. **`process(inputs, context)`**: Execute the loading process, validating inputs, preprocessing, invoking the loader, and postprocessing the results.

### Usage

To use the `PDFLoaderNodeImpl` within the project:

1. **Instantiate the Node:** Call `PDFLoaderNodeImpl.create()` to get a configured loader node for PDFs.
2. **Process Data:** Use the `process` method to load PDF data, providing the necessary inputs and context.

## Extending the `LoaderNode`

Developers can contribute by extending the `LoaderNodeImpl` class to create new loader nodes for different data formats. To do so:

1. **Define a New Loader Class:** Similar to `PDFLoaderNodeImpl`, define a class for the new data format.
2. **Implement Required Methods:** Provide concrete implementations for `_preprocess`, `_postprocess`, `invoke`, and optionally override `process` if needed.
3. **Configure Node Properties:** Set up the node's type, data, visual info, inputs, and outputs according to the data format.

**Comment by VictorS67** [comment]
# Message Nodes

## Overview

This document provides an overview on the Message Nodes within the Encre Studio. These nodes are specialized for handling different types of messages, such as chat, human, bot, system, and function messages.

## `MessageNode` Type

`MessageNode` is a `SerializableNode` that's specified to handle messaging data. It is characterized by a specific `'message'` type and associated with a `BaseMessage` class, which can be extended to support various message formats.

### Key Features

- **Generic Message Type:** Facilitates the creation of message nodes for different roles.
- **Extensibility:** Allows for the easy extension to different new message nodes, such as human message.

## `MessageNodeImpl` Class

`MessageNodeImpl` is an abstract base class for all message node implementations. It extends from `NodeImpl`, providing a foundation for processing inputs and generating outputs specific to message data.

### Processing Method

- **`process(inputs, context)`**: Validates the inputs and returns a message based on the node's configuration. It ensures that the node operates correctly within the given context and adheres to the expected input structure.

## Message Node Implementations

There are several concrete implementations of the `MessageNodeImpl` class, each correspond to a specific type of message:

- `ChatMessageNodeImpl`: Handles chat messages, typically involving user interaction within a chat interface.

- `HumanMessageNodeImpl`: Handles messages generated by human users.

- `BotMessageNodeImpl`: Handles messages generated by bots (e.g. LLMs or ChatLMs).

- `SystemMessageNodeImpl`: Handles prompts for LLMs or ChatLMs.

- `FunctionMessageNodeImpl`: Handles messages for passing the result of executing a function back to LLMs or ChatLMs.

### Creation

- `create()`: Static method to instantiate a MessageNode configured for messages. It sets up the node's type, associated data (message configuration), visual information, inputs, and outputs. This is used for creating a default message node.
  - **Input Ports:** no input port;
  - **Output Ports:** has one port named `message`, allowing a single type: `ChatMessageData`.

### Processing Methods

1. `process(inputs, context)`: Wnsuring no inputs are given, handles the outputs from the message, and return the chat-message data.

## Extending the `MessageNode`

Developers can contribute by extending the `MessageNodeImpl` class to create new message nodes for different data formats. To do so:

1. **Define New Message Node Types:** Create classes that extend `MessageNodeImpl`, providing concrete implementations for different message types as needed.
2. **Implement Custom Logic:** For each new message node type, implement any custom logic required to process or generate messages.
3. **Configure Node Properties:** Appropriately set up the node's type, data, visual information, inputs, and outputs to match the intended message format.

**Review by AlveinTeng — COMMENTED** [review]
Please add more details about each scalar datatypes, since this would be our fundamental data types. And possibly explain why you pick all these as our scalar datatypes.

**Comment by VictorS67** [comment]
# Prompt Nodes

## Overview

This document provides an overview on the Prompt Nodes within the Encre Studio. These nodes are specialized for generating prompts, including string prompts and chat prompts.

## `PromptNode` Type

`PromptNode` is a `SerializableNode` specified for creating prompts. It is characterized by a specific `'prompt'` type, associated with a base class `BasePrompt` which can be extended to accommodate diverse prompt formats.

### Features

- **Generic Message Type:** Facilitates the creation of prompt nodes for inputing models.
- **Extensibility:** Allows for the easy extension to different new prompt nodes, such as string prompt.

## `PromptNodeImpl` Class

`PromptNodeImpl` is an abstract base class for all prompt node implementations. It extends from `NodeImpl`, it encapsulates common functionalities needed for processing prompt-related data.

### Process Method

- **`process(inputs, context)`**: Validates inputs and processes them to generate prompts based on the node's data. It dynamically handles outputs according to connected input types.

## Prompt Node Implementations

There are several concrete implementations of the `PromptNodeImpl` class, each correspond to a specific type of prompt:

- `StringPromptNodeImpl`: Creates string-based prompts, used for simple text interactions.
- `ChatPromptNodeImpl`: Creates chat-based prompts, used for more complex interactions involving multiple chat messages.

### Creation
- `create()`: Static method to instantiate a `PromptNode` configured for prompts. It sets up the node's type, associated data (prompt configuration), visual information, inputs, and outputs. This is used for creating a default prompt node.
  - Input Ports: no input port;
  - Output Ports: has one port named `prompt`, allowing either of the following two types: `StringData`, `ChatMessageData`.

### Processing Methods
1. `process(inputs, context)`: Ensuring no inputs are given, handles the outputs from the prompt, and return the chat-message data. (now it cannot return string data, not finalized yet)

## Extending the `PromptNode`

Developers can contribute by extending the `PromptNodeImpl` class to create new prompt nodes for different data formats. To do so:

1. **Define New Prompt Node Types:** Create classes that extend `PromptNodeImpl`, providing concrete implementations for different prompt types as needed.
2. **Implement Custom Logic:** For each new message node type, implement any custom logic required to process or generate prompts.
3. **Configure Node Properties:** Appropriately set up the node's type, data, visual information, inputs, and outputs to match the intended prompt format.

**Comment by VictorS67** [comment]
# Splitter Nodes

## Overview

This document outlines the implementation and usage of splitter nodes in the Encre Studio class. Splitter nodes supports a callable event extends `ContextSplitter` designed to splitter various types of data. There are various splitting strategies such as text, recursive text, language-specific text, and token-based splitting.

## `SplitterNode` Type

`SplitterNode`  is a specific callable node type intended for splitting operations. It encapsulates functionality for splitting input data (`string`, `context`, or `context[]`) into an array of contexts (`context[]`).

### Key Features

- **Generic Splitter Type:** Facilitates the creation of splitter nodes for various data formats.
- **Extensibility:** Allows for easy extension to accommodate different types of splitters, such as text-splitting, recursive text-splitting, language-specific text-splitting, and token-based splitting.

## `SplitterNodeImpl` Class

`SplitterNodeImpl` is an abstract base class for all splitter node implementations. It extends `CallableNodeImpl`, providing the necessary infrastructure for preprocessing inputs, invoking the splitting operation, and postprocessing outputs.

### Key Methods

- `_preprocess(inputs, context)`: Validates and prepares input data for the splitting operation.
- `_postprocess(rawOutputs, context)`: Converts the raw splitting results into a structured output format.
- `invoke(input, options)`: Performs the splitting operation using the specified input and options.
- `process(inputs, context)`: Orchestrates the entire data splitting process, from input validation to output generation.

## Splitter Node Implementations

There are several concrete implementations of the `SplitterNodeImpl` class, each correspond to a specific splitting strategy:

- `TextSplitterNodeImpl`: Splits text data into parts based on predefined criteria, suitable for general text splitting tasks.
- `RecursiveTextSplitterNodeImpl`: Performs recursive splitting of text data, ideal for nested or hierarchical data structures.
- `LanguageTextSplitterNodeImpl`: Splits text data based on language-specific rules, utilizing `RecursiveTextSplitter.fromLanguage` for initialization.
- `TokenTextSplitterNodeImpl`: Splits text into tokens, typically used for lexical analysis or similar applications.

### Creation

- `create()`: Static method to instantiate a `SplitterNode` configured for text splitting. It sets up the node's type, associated data (splitter configuration), visual information, inputs, and outputs. This is used for creating a default message node.
  - Input Ports: has one port named `input`, allowing either of two types: `StringData`, `ContextData`, array of `ContextData`;
  - Output Ports: has one port named `contexts`, allowing a single type: array of `ContextData`;

### Processing Methods

- `_preprocess(inputs, context)`: Prepares the input data for processing, ensuring it is either a `string`, a `Context` or an array of `Context`. Throws an error for invalid inputs.
- `_postprocess(rawOutputs, context)`: Handles the outputs from the splitting operation, converting them into a structured format suitable for further processing.
- `invoke(input, options)`: Performs the actual splitting operation using the provided input, which must be a `string`, a `Context` or an array of `Context`.
- `process(inputs, context)`: Execute the splitting process, validating inputs, preprocessing, invoking the splitter, and postprocessing the results.

## Extending the `SplitterNode`

Developers can contribute by extending the `SplitterNodeImpl` class to create new splitter nodes for different data formats. To do so:

To contribute to the project by adding new splitter nodes or enhancing existing ones, developers should:

1. **Define a New Splitter Node Class:** Create subclasses of `SplitterNodeImpl` for novel splitting strategies, providing custom implementations as necessary.
2. **Implement Required Methods:** Provide concrete implementations for `_preprocess`, `_postprocess`, `invoke`, and optionally override `process` if needed.
3. **Configure Node Properties:** Set up the node's type, data, visual info, inputs, and outputs according to the data format.

**Comment by VictorS67** [comment]
# Large Language Model (LLM) Nodes

## Overview

This document outlines the implementation and usage of Large Language Model (LLM) nodes in the Encre Studio. LLM nodes supports a callable event extends `BaseLLM` designed for integrating various LLMs. These nodes facilitate the interaction with these models, enabling the generation of text, analysis, and other AI-driven outputs based on input prompts.

## `LLMNode` Type

`LLMNode` is a specialized form of `CallableNode` tailored for operations involving large language models. It signifies nodes that specifically handle interactions with LLMs, offering a structured approach to invoking these models and processing their outputs.

### Key Features

- **Flexibility:** Supports interactions with multiple LLMs, allowing for easy integration of additional models as required.
- **Extensibility:** Designed to be extendable, enabling custom implementations for different LLMs or specific functionalities.

## `LLMNodeImpl` Class

`LLMNodeImpl` is a abstract base class for all LLM node implementations within the framework. Extending `CallableNodeImpl`, it provides a standardized process for preparing input data, invoking the LLM, and processing the LLM's outputs.

### Key Methods

- **`_preprocess(inputs, context)`**: Validates and prepares the input prompt for the LLM, ensuring it meets the expected format.
- **`_postprocess(rawOutputs, context)`**: Transforms the raw outputs from the LLM into a structured format suitable for further processing or output.
- **`invoke(input, options)`**: Invokes the LLM with the prepared input and any specified options, returning the LLM's output.

## LLM Node Implementations

There are several concrete implementations of the `LLMNodeImpl` class, each correspond to a specific LLM:

- `OpenAINodeImpl`: Integrates with OpenAI's models, such as `text-davinci-003`, to generate text based on input prompts.
- `GeminiNodeImpl`: Integrates the Gemini model for generating text, offering an alternative LLM option within the framework.

### Creation

- `create()`: Static method to instantiate a `LLMNode` configured for the specific LLM. It sets up the node's type, associated data (LLM configuration), visual information, inputs, and outputs. This is used for creating a default LLM node.
  - Input Ports: has one port named `prompt`, allowing either of two types: StringData, array of ChatMessageData;
  - Output Ports: has five ports:
    - output, representing the generated output from LLM, allowing a single type: StringData;
    - info, representing additional information of the LLM's generated output, allowing two types: JSONObjectData, or UnknownData (optionally undefined);
    - completionTokens, representing the number of tokens used for completion, allowing two types: NumberData, or UnknownData (optionally undefined);
    - promptTokens, representing the number of tokens used for prompt, allowing two types: NumberData, or UnknownData (optionally undefined);
    - totalTokens, representing the number of tokens used for prompt and completion, allowing two types: NumberData, or UnknownData (optionally undefined).

## Extending the `LLMNode`

Developers can contribute by extending the `LLMNodeImpl` class to create new prompt nodes for different data formats. To do so:

1. **Defining New LLM Node Classes:** Create new subclasses of `LLMNodeImpl` for additional LLMs or customized functionalities.
2. **Implementing Required Methods:** Provide concrete implementations for `_preprocess`, `_postprocess`, `invoke`, and `process` methods.
3. **Configuring Node Properties:** Set up the node's type, associated LLM data, visual information, inputs, and outputs according to the LLM's requirements.

**Comment by VictorS67** [comment]
# Chat Large Language Model (ChatLM) Nodes

## Overview

This document outlines the implementation and usage of Chat Large Language Model (ChatLM) nodes in the Encre Studio. ChatLM nodes supports a callable event extends ChatLM designed for integrating various chat models. These nodes facilitate the interaction with these models, enabling the generation and processing of conversational content based on input prompts.

## `ChatLMNode` Type

`ChatLMNode` is a specialized form of `CallableNode` tailored for operations involving chat-oriented LLMs. It signifies nodes that specifically handle conversational interactions, generating responses based on varying input prompts.

### Key Features

- **Flexibility:** Supports interactions with multiple ChatLMs, allowing for easy integration of additional models as required.
- **Extensibility:** Designed to be extendable, enabling custom implementations for different ChatLMs or specific functionalities.

## `ChatLMNodeImpl` Class

`ChatLMNodeImpl` is a abstract base class for all chat LLM node implementations. It extends `CallableNodeImpl` to provide a structured approach to preprocessing input data, invoking chat LLMs, and postprocessing their outputs.

### Key Methods

- **`_preprocess(inputs, context)`**: Validates and prepares the input prompts for the LLM, ensuring compatibility.
- **`_postprocess(rawOutputs, context)`**: Formats the raw outputs from the LLM into a structured, consumable format for subsequent processing or interaction.
- **`invoke(input, options)`**: Executes the chat LLM call, passing the prepared input along with any specified options.

## ChatLM Node Implementations

There are several concrete implementations of the `ChatLMNodeImpl` class, each correspond to a specific ChatLM:

- `OpenAIChatNodeImpl`: Integrates with OpenAI's chat models (e.g., `gpt-3.5-turbo`), facilitating rich conversational interactions.
- `GeminiChatNodeImpl`: Integrates the Gemini chat model for generating conversational content, offering an alternative to OpenAI's offerings.

### Creation

- `create()`: Static method to instantiate a `ChatLMNode` configured for the specific ChatLM. It sets up the node's type, associated data (ChatLM configuration), visual information, inputs, and outputs. This is used for creating a default ChatLM node.
  - Input Ports: has one port named `prompt`, allowing either of two types: StringData, array of ChatMessageData;
  - Output Ports: has six ports:
    - output, representing the generated output from ChatLM in text, allowing a single type: StringData;
    - message, representing the generated output from ChatLM in a message, allowing a single type: ChatMessageData; 
    - info, representing additional information of the ChatLM's generated output, allowing two types: JSONObjectData, or UnknownData (optionally undefined);
    - completionTokens, representing the number of tokens used for completion, allowing two types: NumberData, or UnknownData (optionally undefined);
    - promptTokens, representing the number of tokens used for prompt, allowing two types: NumberData, or UnknownData (optionally undefined);
    - totalTokens, representing the number of tokens used for prompt and completion, allowing two types: NumberData, or UnknownData (optionally undefined).

## Extending the `ChatLMNode`

Developers can contribute by extending the LLMNodeImpl class to create new prompt nodes for different data formats. To do so:

1. **Define New ChatLM Node Classes:** Create subclasses of `ChatLMNodeImpl` for new LLMs or custom functionalities, implementing the required logic for interaction.
2. **Implementing Required Methods:** Provide concrete implementations for `_preprocess`, `_postprocess`, `invoke`, and `process` methods.
3. **Configuring Node Properties:** Set up the node's type, associated ChatLM data, visual information, inputs, and outputs according to the ChatLM's requirements.

**Review by VictoriaXie — APPROVED** [review]

**Review by BenWXY — APPROVED** [review]

**Review by BenWXY — APPROVED** [review]

**Pull request merged**
