### PR TITLE
Add wire to connect between nodes

### PR DESCRIPTION
**Pull request by VictorS67**
- Added multiple wire types: 
  - Straight: the straight line from port A to port B.
  - Bezier: the [Bézier curve](https://en.wikipedia.org/wiki/B%C3%A9zier_curve) from port A to port B.
  - Smooth Step: the step line from port A to port B, where there are curves around step points.
  - Adaptive Bezier: the [Bézier curve](https://en.wikipedia.org/wiki/B%C3%A9zier_curve) with wider curvature but keep the center line to be more straight.
- Added some animation when selecting wires or hovering wires.
- Dragging output ports in node will create new wires for connecting to input ports, but currently we only support one wire to each input port. If a new wire connects to the port that is already connected, then the old wire will be removed. Demo A below is showing this scenario.
- Dragging input ports in node will detach any connected wires to the ports. In this way, a connected wire can be cancelled. Demo B below is showing this scenario.

TODO:
- Need to check if the node connections are causing a cyclic graph when creating new connections.
- Allow each wire to change its type, currently we use Adaptive Bezier as default.
- Support context-menu opening for the wire port.
- Need more restrict rule for creating new connections, such as user should only create new connections if two ports share the same data type. Also need coloring on ports and wires to show the differences of the data types,

Demo A:
firefox_j79drnamkV

Demo B:
firefox_POdXh25y8K

### CODE REVIEW

**Review by AlveinTeng — COMMENTED** [review]
why we need straight lines, considering that we already have Bézier curves

**Comment by VictorS67** [comment]
> why we need straight lines, considering that we already have Bézier curves

Just giving user options to change the visualization of the wire, we have Bézier curves in default

**Comment by BenWXY** [comment]
"If a new wire connects to the port that is already connected, then the old wire will be removed."
Is this a rule for our case? Could one port receive data from different node?

**Comment by VictorS67** [comment]
> "If a new wire connects to the port that is already connected, then the old wire will be removed."
> Is this a rule for our case? Could one input port receive data from different nodes?

Yeah. This is the rule. For simplicity, we only allow one connection for each input port. 

One input port **cannot** receive data from different nodes. The reason for this rule is that the processing situations are much more complex if one input has more than one data source. Let's say port A and port B connects to an input port C, some situations can be:
1. In the process run time, we are not sure the time order of getting data from port A and data from port B, which means we should decide whether input port C should wait for both A and B to send the data;
2. Continued from the situation 1, let's say input port C should wait for both A and B, then we should decide how the data should be merged from A's data and B's data. This involves considering the type of the data. For example, if input port C support type `Blob` or `string`, but A's data has type `Blob` and B's data has type `string`, then we need to align A's and B's data into the same type and then merge them.
3. Continued from the situation 2, let's say input port C can be processed with either A's data or B's data, then we should decide whether the node with the port C can be triggered multiple times. For example, if the node with the port C can only run once, then the node will ignore B's data if A's data arrives first. Otherwise, if the node with the port C can run multiple times, then both A and B can trigger the node with the port C regardless of the time order.

Those situations should be fully considered. So allowing port receiving multiple data source requires much more embedded rules, which increases the user's learning curve.

**Comment by VictorS67** [comment]
> And wha does the circle in the middle of the curve mean?

The circle in the middle of the curve can trigger the context menu on the wire. In the case, we don't need to use right click for opening context menu on wires.

**Review by BenWXY — APPROVED** [review]

**Review by AlveinTeng — APPROVED** [review]

**Pull request merged**
